// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-iz9KK_jk9HoORMa-PszLl9BAYgZqPsE',
    appId: '1:739217217147:web:4c1038d57500ff808e74de',
    messagingSenderId: '739217217147',
    projectId: 'tubes1-1',
    authDomain: 'tubes1-1.firebaseapp.com',
    databaseURL: 'https://tubes1-1-default-rtdb.firebaseio.com',
    storageBucket: 'tubes1-1.appspot.com',
    measurementId: 'G-MK97MBXL73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHNYkWGUxwaR7nh0geuKpyn-9XfoIqd30',
    appId: '1:739217217147:android:014ba5b34475d2d18e74de',
    messagingSenderId: '739217217147',
    projectId: 'tubes1-1',
    databaseURL: 'https://tubes1-1-default-rtdb.firebaseio.com',
    storageBucket: 'tubes1-1.appspot.com',
  );
}
